#include "bn_ctype.h"

/*
 * 数组仅覆盖0-127(7位ASCII)，共128个元素 —— 对应所有ASCII字符
 * 字符集先转成ASCII再查表，保证索引合法
 * 安全防护：先检查字符是否在0-127范围内，再用它当作数组下表，避免访问越界
 */
static const unsigned short bn_ctype_map[128] = {
    /* 00 nul */ BN_CTYPE_CNTRL,
    /* 01 soh */ BN_CTYPE_CNTRL,
    /* 02 stx */ BN_CTYPE_CNTRL,
    /* 03 etx */ BN_CTYPE_CNTRL,
    /* 04 eot */ BN_CTYPE_CNTRL,
    /* 05 enq */ BN_CTYPE_CNTRL,
    /* 06 ack */ BN_CTYPE_CNTRL,
    /* 07 \a  */ BN_CTYPE_CNTRL,
    /* 08 \b  */ BN_CTYPE_CNTRL,
    /* 09 \t  */ BN_CTYPE_SPACE | BN_CTYPE_BLANK | BN_CTYPE_CNTRL,
    /* 0A \n  */ BN_CTYPE_SPACE | BN_CTYPE_CNTRL,
    /* 0B \v  */ BN_CTYPE_SPACE | BN_CTYPE_CNTRL,
    /* 0C \f  */ BN_CTYPE_SPACE | BN_CTYPE_CNTRL,
    /* 0D \r  */ BN_CTYPE_SPACE | BN_CTYPE_CNTRL,
    /* 0E so  */ BN_CTYPE_CNTRL,
    /* 0F si  */ BN_CTYPE_CNTRL,
    /* 10 dle */ BN_CTYPE_CNTRL,
    /* 11 dc1 */ BN_CTYPE_CNTRL,
    /* 12 dc2 */ BN_CTYPE_CNTRL,
    /* 13 dc3 */ BN_CTYPE_CNTRL,
    /* 14 dc4 */ BN_CTYPE_CNTRL,
    /* 15 nak */ BN_CTYPE_CNTRL,
    /* 16 syn */ BN_CTYPE_CNTRL,
    /* 17 etb */ BN_CTYPE_CNTRL,
    /* 18 can */ BN_CTYPE_CNTRL,
    /* 19 em  */ BN_CTYPE_CNTRL,
    /* 1A sub */ BN_CTYPE_CNTRL,
    /* 1B esc */ BN_CTYPE_CNTRL,
    /* 1C fs  */ BN_CTYPE_CNTRL,
    /* 1D gs  */ BN_CTYPE_CNTRL,
    /* 1E rs  */ BN_CTYPE_CNTRL,
    /* 1F us  */ BN_CTYPE_CNTRL,
    /* 20 ' ' */ BN_CTYPE_SPACE | BN_CTYPE_BLANK | BN_CTYPE_PRINT | BN_CTYPE_ASN1PRINT,
    /* 21  !  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 22  "  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 23  #  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 24  $  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 25  %  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 26  &  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 27  '  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 28  (  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 29  )  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 2A  *  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 2B  +  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 2C  ,  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 2D  -  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 2E  .  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 2F  /  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT | BN_CTYPE_BASE64,
    /* 30  0  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 31  1  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 32  2  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 33  3  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 34  4  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 35  5  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 36  6  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 37  7  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 38  8  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 39  9  */ BN_CTYPE_DIGIT | BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 3A  :  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 3B  ;  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 3C  <  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 3D  =  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 3E  >  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 3F  ?  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT | BN_CTYPE_ASN1PRINT,
    /* 40  @  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 41  A  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 42  B  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 43  C  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 44  D  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 45  E  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 46  F  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 47  G  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 48  H  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 49  I  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 4A  J  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 4B  K  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 4C  L  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 4D  M  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 4E  N  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 4F  O  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 50  P  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 51  Q  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 52  R  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 53  S  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 54  T  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 55  U  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 56  V  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 57  W  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 58  X  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 59  Y  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 5A  Z  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_UPPER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 5B  [  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 5C  \  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 5D  ]  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 5E  ^  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 5F  _  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 60  `  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 61  a  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 62  b  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 63  c  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 64  d  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 65  e  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 66  f  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_XDIGIT | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 67  g  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 68  h  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 69  i  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 6A  j  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 6B  k  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 6C  l  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 6D  m  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 6E  n  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 6F  o  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 70  p  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 71  q  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 72  r  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 73  s  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 74  t  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 75  u  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 76  v  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 77  w  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 78  x  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 79  y  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 7A  z  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_LOWER | BN_CTYPE_BASE64 | BN_CTYPE_ASN1PRINT,
    /* 7B  {  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 7C  |  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 7D  }  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 7E  ~  */ BN_CTYPE_GRAPH | BN_CTYPE_PRINT | BN_CTYPE_PUNCT,
    /* 7F del */ BN_CTYPE_CNTRL
};

int bn_ctype_check(int c, unsigned int mask)
{
    const int max = sizeof(bn_ctype_map) / sizeof(bn_ctype_map[0]);
    const int a = BN_TOASCII(c);

    return ((a >= 0) && (a < max) && ((bn_ctype_map[a] & mask) != 0));
}

#define ASCII_IS_DIGIT(c)   ((c) >= 0x30 && (c) <= 0x39)
#define ASCII_IS_UPPER(c)   ((c) >= 0x41 && (c) <= 0x5A)
#define ASCII_IS_LOWER(c)   ((c) >= 0x61 && (c) <= 0x7A)

int bn_is_digit(char c)
{
    int a = BN_TOASCII(c);
    return ASCII_IS_DIGIT(a);
}

int bn_is_upper(char c)
{
    int a = BN_TOASCII(c);
    return ASCII_IS_UPPER(a);
}

int bn_is_lower(char c)
{
    int a = BN_TOASCII(c);
    return ASCII_IS_LOWER(a);
}

int bn_ascii_is_digit(char c)
{
    return ASCII_IS_DIGIT(c);
}

/* 编译阶段会计算完成，在运行时该变量不会有任何计算开销 */
static const int ascii_case_diff = (('a' - 'A') > 0) ? ('a' - 'A') : -('a' - 'A');

int bn_to_lower(char c)
{
    int a = BN_TOASCII(c);
    return ASCII_IS_UPPER(a) ? c ^ ascii_case_diff : c;
}

int bn_to_upper(char c)
{
    int a = BN_TOASCII(c);
    return ASCII_IS_LOWER(a) ? c ^ ascii_case_diff : c;
}
